# Site settings
title: Antelio I. Abe
description: Geek and SAP Adicted
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Antelio I. Abe
user_description:
user_title: SAP Architecture, Consultant, Developer and System Administrator
email: antelio@gmail.com
twitter_username: antelio
github_username:  antelio
linkdein_profiel: antelio
gplus_username:  antelio

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
